name: geotess-dev
channels:
- conda-forge
dependencies:
- python=3
- setuptools
- geotesscpp>=2.7
- numpy
- cython=3
- pytest
- make
- myst-parser
- pydata-sphinx-theme
- sphinx >= 5.0
- sphinx-book-theme
- sphinx-autobuild
- pip
  - -e .
# - cxx-compiler
