[build-system]
requires = ["setuptools", "cython", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "pygeotess"
version = "0.3.0"

# [tool.setuptools]
# ext-modules = [
#   {name = "example", sources = ["example.pyx"]}
# ]
