"""
Test GeoTessModel methods.

"""
import datetime
from pathlib import Path

import pytest

import geotess.lib as lib

testdata = Path(__file__).parents[0] / 'testdata'
grid_id = '808785948EB2350DD44E6C29BDEA6CAE'

@pytest.fixture(scope="module")
def crust20():
    inputfile = str(testdata / 'crust20.geotess')
    model = lib.GeoTessModel()
    model.loadModel(inputfile)
    # XXX: loadModel crashes if the associated grid file isn't found.  do a try/except somewhere.
    return model

# @pytest.fixture
# def small_grid():
#     inputfile = str(testdata / 'small_model_grid.ascii')
#     grid = lib.GeoTessGrid()
#     grid.loadGrid(inputfile)
#     return grid

def test_init_empty():
    model = lib.GeoTessModel()
    del model

# @pytest.fixture
# def model2d():
#     """ A small model made from scratch.
#     """
#     md = lib.GeoTessMetaData()
#     md.setDescription("2D velocity model")
#     md.setLayerNames("surface")
#     md.setAttributes("PSLOWNESS; PVELOCITY", "sec/km; km/sec")
#     md.setDataType('FLOAT')
#     md.setModelSoftwareVersion("test_geotessmodel.test_init_from_scratch")
#     # e.g. 'Wed April 18 15:21:51 2012'
#     md.setModelGenerationDate(
#               datetime.datetime.now(tz=datetime.UTC).strftime('%a %B %d %H:%M:%S %Y')
#     )
#     model2d = lib.GeoTessModel(str(testdata / 'small_model_grid.ascii'), md)
#     nvtx = model2d.getGrid().getNVertices()
#     values = [0.125, 8]
#     for vtx in range(nvtx):
#         # model2d.setProfile(vtx, values, 2) # TODO: expose this setProfile interface
#         pass

# @pytest.fixture
# def euler():
#     equal = lib.GeoTessModel()
#     equal.loadModel(str(testdata / 'euler_model_grid_coords_equal.geotess'))
#     unequal = lib.GeoTessModel()
#     unequal.loadModel(str(testdata / 'euler_model_grid_coords_not_equal.geotess'))
#     return equal, unequal

def test_getNAttributes(crust20):
    # model = model_object
    # expected = 3
    # nattributes = model.getNAttributes()
    # assert nattributes == expected
    assert crust20.getNAttributes() == 3

def test_getGrid(crust20):
    grid = crust20.getGrid()
    # expected = 'GeoTessGrid\ngridID = 808785948EB2350DD44E6C29BDEA6CAE\nmemory : 34.0625 MB\ninput Grid File : GeoTessModels/geotess_grid_01000.geotess\ngenerated by software version : GeoModel 7.0.1  Wed April 18 15:21:51 2012\n\nnTessellations = 1\nnLevels = 7\nnVertices = 40962\nnTriangles = 109220\n\n    Tess    Level  LevelID     NTri    First   Last+1\n      0        0        0       20        0       20\n      0        1        1       80       20      100\n      0        2        2      320      100      420\n      0        3        3     1280      420     1700\n      0        4        4     5120     1700     6820\n      0        5        5    20480     6820    27300\n      0        6        6    81920    27300   109220\n\n'
    # assert grid.toString() == expected
    assert grid.getGridID() == '808785948EB2350DD44E6C29BDEA6CAE'

def test_getPointWeights(crust20):
    # randomly chose a lat/lon/depth.
    lat, lon, depth = 30.5, 110.5, 1.0
    expected = {
        142055: 0.25024172435496234, 
        142062: 0.32783477321661203, 
        142069: 0.42192350242842563
        }
    weights = crust20.getPointWeights(lat, lon, depth)
    assert weights == pytest.approx(expected)

# pos = self.thisptr.getPosition(deref(horizontalInterpolator), deref(radialInterpolator))
# def test_EulerInterpolator(euler):
#     euler_model_grid_coords_equal, euler_model_grid_coords_not_equal = euler
#     GeoTessPosition* peq = euler_model_grid_coords_equal->getPosition(GeoTessInterpolatorType::LINEAR, GeoTessInterpolatorType::LINEAR);
#     GeoTessPosition* pneq = euler_model_grid_coords_not_equal->getPosition(GeoTessInterpolatorType::LINEAR, GeoTessInterpolatorType::LINEAR);