site_name: PyGeoTess
site_url: http://lanl-seismoacoustics.github.io/pygeotess
site_description: Python interface to the GeoTess earth model library
site_author: Jonathan K. MacCarthy

copyright: Copyright 2016. Los Alamos National Security, LLC

repo_url: https://github.com/lanl-seismoacoustics/pygeotess

theme: 'readthedocs'
docs_dir: 'src/pages'

markdown_extensions:
    - toc:
        permalink: True
    - fenced_code

pages:
- 'Introduction': 'index.md'
- 'Grids': 'grids.md'
- 'Models': 'models.md'
- 'License': 'license.md'
